[server]
; Grafana 접속 주소 (IP:포트로 접속 시 애플리케이션 파일 로드 실패 방지)
domain = grafana.azas-dash.shop
root_url = http://3.34.166.82:3001/

[security]
; Grafana 앱을 외부 사이트에서 iframe으로 임베드 허용
allow_embedding = true
; 쿠키 SameSite 정책을 none 으로 설정 (임베드 시 세션 공유 이슈 방지)
cookie_samesite = none
cookie_secure = true

[auth.anonymous]
; 로그인 없이 대시보드 조회 허용
enabled = true
org_name = Main Org.
org_role = Viewer
